name: 'Linter + Formatter'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./2LEIC06T5
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.16.5
          cache: true
      - run: dart format . --set-exit-if-changed
  formatter: 
    name: Formatter
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./2LEIC06T5
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.16.5
          cache: true
      - run: flutter analyze